version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    ports:
      - 8888:8888
    labels:
      - homepage.group=Synology-NAS
      - homepage.name=Jupyter Notebook
      - homepage.icon=jupyter
      - homepage.href=http://synas:8888/
      - homepage.description=Jupyter Notebook
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="
